// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20241026170946_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "admodum fabulae epicuro scriptorem perdiscere error texit maximi angusta facilis expetendum possint afferat integris imperitorum miraretur situm si comparaverit superstitione nullus admonitionem naturae artem voluptates claudicare a euripidis monstret",
                            ImgUri = "/pictures/1.jpg",
                            Name = "tolerabiles dui expectata",
                            Price = 8489.11m
                        },
                        new
                        {
                            Id = 2,
                            Description = "gravida rebus huc recusabo quietae pulcherrimum amice praeceptrice falsis inceptos summumque fructuosam iuberet interrogare fugiamus iucundum arbitratu concederetur inciderit",
                            ImgUri = "/pictures/2.jpg",
                            Name = "pretium tradit temperantiam etsi",
                            Price = 3734.43m
                        },
                        new
                        {
                            Id = 3,
                            Description = "mel error neglegentur via difficilem navigandi homero risus potiora videro amatoriis quo insolens aperiam finxerat compluribus morbis erat domesticarum operam certa putant libero sententia deterret falsis",
                            ImgUri = "/pictures/3.jpg",
                            Name = "vulputate praetermittatur dicant",
                            Price = 4051.37m
                        },
                        new
                        {
                            Id = 4,
                            Description = "oriantur minuti minus directam iste consequentis aristotelem iuvaret priventur alii artes opera laudabilis imperitos mortis alia acutum quippiam errem",
                            ImgUri = "/pictures/4.jpg",
                            Name = "recte invidus ullus",
                            Price = 551.94m
                        },
                        new
                        {
                            Id = 5,
                            Description = "quippe quaerendi putas suspicio tueri nemini fatendum quin laetitia habendus desiderent suis scaevola stoicis viris legum remotis lineam nisi aliter chorusque admodum illis obcaecati euripidis pacuvii",
                            ImgUri = "/pictures/5.jpg",
                            Name = "plusque inventore modis praeclare",
                            Price = 3110.51m
                        },
                        new
                        {
                            Id = 6,
                            Description = "curis voluptas sero incidunt placuit habendus exercitationem necesse reperiuntur inanium praetorem soliditatem accedunt aliquid gaudere consecutus curiosi tenent exorsus eae tempus urna veritus persecuti perspecta",
                            ImgUri = "/pictures/6.jpg",
                            Name = "corrigere consumeret",
                            Price = 8748.69m
                        },
                        new
                        {
                            Id = 7,
                            Description = "copiosae nostro praesentium deorsus detracto aliquet hendrerit credere musicis delectari delectat potest cupiditatibusque euripidis dixi adipiscendarum graecum doctus consuevit ipsis caritatem",
                            ImgUri = "/pictures/7.jpg",
                            Name = "ferentur commodi mortis efficiendi",
                            Price = 201.41m
                        },
                        new
                        {
                            Id = 8,
                            Description = "procedat turbulentaeque amentur cursu adolescens locum seditiones mens disseruerunt effluere se consuetudine ceteris",
                            ImgUri = "/pictures/8.jpg",
                            Name = "suscipit sponte discordia aiunt",
                            Price = 447.86m
                        },
                        new
                        {
                            Id = 9,
                            Description = "quorum graecis inducitur provincias veritus statue improborum renovata iudicia exercitationem praeterierunt singulos versuum data",
                            ImgUri = "/pictures/9.jpg",
                            Name = "praetermittatur praeclarorum aristotele plus",
                            Price = 5943.6m
                        },
                        new
                        {
                            Id = 10,
                            Description = "dedecora fere procedat accusator primus massa bonorum amorem persequeretur geometriaque compluribus saperet contrariis",
                            ImgUri = "/pictures/10.jpg",
                            Name = "orationis disputationi maximasque admirer",
                            Price = 6497.61m
                        },
                        new
                        {
                            Id = 11,
                            Description = "cursus asperner excepturi multo praesidium ferentur dixeris liber impendere solido vetuit disputando condimentum iudico corpus anteponant",
                            ImgUri = "/pictures/11.jpg",
                            Name = "disserui quocirca",
                            Price = 3146.42m
                        },
                        new
                        {
                            Id = 12,
                            Description = "admonitionem illis quid graecum chrysippi ceteris cupiditate terrore perturbari varius ultricies beateque fecisse antipatrum ipsos plus munere interpretum",
                            ImgUri = "/pictures/12.jpg",
                            Name = "aliquando infantes offendimur",
                            Price = 9014.08m
                        },
                        new
                        {
                            Id = 13,
                            Description = "reque mandamus sumus veniamus quaeso opera videntur reprehensione conscientia studuisse conversa paranda",
                            ImgUri = "/pictures/13.jpg",
                            Name = "iuvaret iusteque exercitus persequeretur",
                            Price = 4227.49m
                        },
                        new
                        {
                            Id = 14,
                            Description = "netus praetor tenuit aiebat conscientiam referta incurrunt philosophorum filio triarius minuit",
                            ImgUri = "/pictures/14.jpg",
                            Name = "desiderare noctesque discenda",
                            Price = 9905.62m
                        },
                        new
                        {
                            Id = 15,
                            Description = "optinere miserum mihi dicunt dicas confirmavit an vindicet concordia urbanitas intervalla suscepi saepti copulationesque gratissimo simplicem quale imperiis summa morbis quin bonum paria pueri",
                            ImgUri = "/pictures/15.jpg",
                            Name = "confirmat uberius plerumque",
                            Price = 1208.82m
                        },
                        new
                        {
                            Id = 16,
                            Description = "fuga accessio ullam interesset tria sumus officia amicitiae acri siculis interesset permanentes traditur suspicor deleniti fabulas malivoli suavitate",
                            ImgUri = "/pictures/16.jpg",
                            Name = "duce illaberetur posidonium",
                            Price = 9840.82m
                        },
                        new
                        {
                            Id = 17,
                            Description = "potest animumque cn utramque mauris tibique rudem quia vacuitate praeterita falli modis quantus ultimum loco impetu superstitione eligendi proin respirare putat miseram imitarentur",
                            ImgUri = "/pictures/17.jpg",
                            Name = "mandaremus postremo",
                            Price = 3602.11m
                        },
                        new
                        {
                            Id = 18,
                            Description = "gravissimis discedere contineret pertinacia petat elit summo fecisse videri factorum praesens difficilius dirigentur tamque principes ferentur fieri cn doloribus renovata class vocet tantalo repellere terentii titillaret consectetuer odia",
                            ImgUri = "/pictures/18.jpg",
                            Name = "simulent depravatum intellegimus impetum",
                            Price = 4309.92m
                        },
                        new
                        {
                            Id = 19,
                            Description = "habet soluta minuti labor corpus sumus assueverit pacto omnium atomorum tertium uterque aequitate momenti litteras perciperet perpetua maximo laudantium",
                            ImgUri = "/pictures/19.jpg",
                            Name = "bonis felis",
                            Price = 5954.44m
                        },
                        new
                        {
                            Id = 20,
                            Description = "hae falsarum fortunam quocirca quidem concupiscunt dixeris cognita sublata vivi ecce sensum fugiamus exquirere disputationi corrupti interiret amet necessitatibus consul allicit attento utamur quisquam exultat",
                            ImgUri = "/pictures/20.jpg",
                            Name = "delectet nulli",
                            Price = 5061.92m
                        },
                        new
                        {
                            Id = 21,
                            Description = "dolorem dixit quale assumenda cumanum consul restat captiosa esse libidinosarum haec velint aiebat velim prorsus probarent consuevit filium inimicus graeci altera",
                            ImgUri = "/pictures/21.jpg",
                            Name = "invidiae utilitate parvos",
                            Price = 6631.04m
                        },
                        new
                        {
                            Id = 22,
                            Description = "evertunt habent monstruosi instructus gustare parum eruditionem integer eo prima aegritudo artis eoque conquisitis atomorum fruenda fortitudinis probarentur atomus quamquam atomi animus viveremus aliam",
                            ImgUri = "/pictures/22.jpg",
                            Name = "naturalem interpretum",
                            Price = 3734.79m
                        },
                        new
                        {
                            Id = 23,
                            Description = "me deterruisset ornare erudito faciant stabilitas quantum difficilius optimus tite simplicem beate laudabilis probaturum dictum",
                            ImgUri = "/pictures/23.jpg",
                            Name = "diligi class lectorem",
                            Price = 8850.98m
                        },
                        new
                        {
                            Id = 24,
                            Description = "perdiderunt et liberae placebit patiatur docti hominum manus specie conspiratione",
                            ImgUri = "/pictures/24.jpg",
                            Name = "partus stabilique deorsus fructuosam",
                            Price = 3975.19m
                        },
                        new
                        {
                            Id = 25,
                            Description = "fuerit queo vel efficiat exeamus concedo posse scelerisque difficilem penitus molestias exercitumque quaeso esset tortor fortitudo tite confirmare effecerit studiis",
                            ImgUri = "/pictures/25.jpg",
                            Name = "referuntur conversa primis",
                            Price = 5484.01m
                        },
                        new
                        {
                            Id = 26,
                            Description = "perfunctio quis putet eveniet eripuit factorum acutus ponatur fructuosam synephebos timentis triario animadvertat sublatum veritus is eodem",
                            ImgUri = "/pictures/26.jpg",
                            Name = "concursionibus necessitatibus pariendarum noster",
                            Price = 1656.89m
                        },
                        new
                        {
                            Id = 27,
                            Description = "diu usus referri occultarum oriantur tamen sis neque diesque corporisque eriguntur pacuvii ullamcorper instituendarum tu arbitraretur totam graece dissentiunt etiamsi antiquis ulla",
                            ImgUri = "/pictures/27.jpg",
                            Name = "beata ullum",
                            Price = 5290.16m
                        },
                        new
                        {
                            Id = 28,
                            Description = "hac testibus indignae sicine mollitia mirari percipiatur probabis incurrunt secutus veriusque",
                            ImgUri = "/pictures/28.jpg",
                            Name = "inopem vitam",
                            Price = 9386.88m
                        },
                        new
                        {
                            Id = 29,
                            Description = "potuimus noster easque ceteris inane alios ignorant fruuntur operosam servata offendit modus",
                            ImgUri = "/pictures/29.jpg",
                            Name = "operosam infimum consequi calere",
                            Price = 812.83m
                        },
                        new
                        {
                            Id = 30,
                            Description = "menandro laudari usu corporum gloriatur munere praesens vindicet deleniti aeque breviter breviter distrahi principes repellere consequuntur vacuitate reperiri eveniet se possim videretur",
                            ImgUri = "/pictures/30.jpg",
                            Name = "torqueantur ferant",
                            Price = 1907.2m
                        },
                        new
                        {
                            Id = 31,
                            Description = "amarissimam contenta cognomen timidiores notissima aiebat atomorum turpe deorsus triarius putas commodo synephebos epicureum theseo iactant turbulenta exercendi clariora terroribus amorem iucundo notissima laudem",
                            ImgUri = "/pictures/31.jpg",
                            Name = "studia aetatis iudex turma",
                            Price = 3468.06m
                        },
                        new
                        {
                            Id = 32,
                            Description = "armatum consentaneum synephebos ostendit abest ullum alteram tamquam dapibus ista diam ornare solum usus afferat amicum crudelis uberius imperii arbitrer",
                            ImgUri = "/pictures/32.jpg",
                            Name = "levis tua mortis",
                            Price = 6199.77m
                        },
                        new
                        {
                            Id = 33,
                            Description = "percipitur mediocris maiores nostrum erudito causam bonae labore homero comprobavit",
                            ImgUri = "/pictures/33.jpg",
                            Name = "ullum populo fuga",
                            Price = 995.03m
                        },
                        new
                        {
                            Id = 34,
                            Description = "legerint propterea seditione temeritate doctrina cupiditate magnitudinem nati intelleges indoctis modo legendum libero virtutem comparandae ineruditus locatus obcaecati explicari gravissimis laetetur efficiat summo fusce cogitavisse consuetudine invidi",
                            ImgUri = "/pictures/34.jpg",
                            Name = "sollicitudin ipsas suspicor fieri",
                            Price = 5033.29m
                        },
                        new
                        {
                            Id = 35,
                            Description = "defendit amorem dedecora studio interrogare quasi laboriosam aegritudo unam contemnit sollicitare",
                            ImgUri = "/pictures/35.jpg",
                            Name = "disseretur cupiditates plerumque amoris",
                            Price = 7004.69m
                        },
                        new
                        {
                            Id = 36,
                            Description = "fecerit familiarem sentiunt militaris veritus futurove disciplinae solis interea quietus",
                            ImgUri = "/pictures/36.jpg",
                            Name = "moveat videretur ii",
                            Price = 2875.75m
                        },
                        new
                        {
                            Id = 37,
                            Description = "ego prima longinquitate industria explicatam turpius ulla menandro appetendi sit scientia frui medeam chorusque aenean sensus magnam",
                            ImgUri = "/pictures/37.jpg",
                            Name = "ponunt praeclaram",
                            Price = 4966.45m
                        },
                        new
                        {
                            Id = 38,
                            Description = "sententiae sociis istae causae sapienti restincto fabulae ii persius pendet ratione erit multos successionem complexiones ac consentinis ornare iracundia apud quis egestas vituperata probatus necesse sale coerceri sentit",
                            ImgUri = "/pictures/38.jpg",
                            Name = "antiquis restincto",
                            Price = 6863.03m
                        },
                        new
                        {
                            Id = 39,
                            Description = "insidiarum industriae statue angusti faciant latinas cohaerescent nocet consentientis generis cur alliciat architecto verentur diogenem supplicii senectus greges loca monet pronuntiaret class mentitum statim privatione laudem accusamus pertinaces",
                            ImgUri = "/pictures/39.jpg",
                            Name = "disserendum torquate oritur",
                            Price = 8245.12m
                        },
                        new
                        {
                            Id = 40,
                            Description = "gravissimis conducunt initia doloremque utramque sanguinem consequuntur fidem insipientiam occulta tempus reprehensione",
                            ImgUri = "/pictures/40.jpg",
                            Name = "recta ingeniis putas",
                            Price = 154.07m
                        },
                        new
                        {
                            Id = 41,
                            Description = "sitisque hae artes conturbamur facilius status abhorreant exiguam scaevolam laborat industria collegi formidinum tribuat imperitos teneam perpaulum scientia ratione obcaecati superstitio metus gaudere dignitatis eram",
                            ImgUri = "/pictures/41.jpg",
                            Name = "maestitiam silano suscepi valetudinis",
                            Price = 9373.96m
                        },
                        new
                        {
                            Id = 42,
                            Description = "consiliisque remissius locus accusamus motus fuga appetendum dicam reprimique minuti dolere officii volumus ostendit timeret exquisitaque effecerit vicinum grate reliquarum siculis afficit caeco extremo tantas epicureum adversa sentio statua",
                            ImgUri = "/pictures/42.jpg",
                            Name = "pararetur arbitrer alienus",
                            Price = 4200.84m
                        },
                        new
                        {
                            Id = 43,
                            Description = "officia naturales finitum ferae aperiam sentire interpretum aegritudo detraxit futuros dixeris miserius posuere expectamus verterunt detraxisse",
                            ImgUri = "/pictures/43.jpg",
                            Name = "deterritum turbulentaeque eius sinat",
                            Price = 7620.29m
                        },
                        new
                        {
                            Id = 44,
                            Description = "delicatissimi celeritas erigimur feugiat dicant fere vera fodere expeteretur fit conetur exercitumque efficit praesidium torquatum o explicabo valetudinis graviterque accusantium summis vacare optari",
                            ImgUri = "/pictures/44.jpg",
                            Name = "perpetuis discidia class collegi",
                            Price = 274.78m
                        },
                        new
                        {
                            Id = 45,
                            Description = "divitias amori primum detracto uberiora hominem dissident angere ponit nullus claris apeirian sola angoribus talem incurrunt huc amatoriis dissentias eros",
                            ImgUri = "/pictures/45.jpg",
                            Name = "eruditi litteris tempus numquidnam",
                            Price = 8494.42m
                        },
                        new
                        {
                            Id = 46,
                            Description = "cn rudem diuturnitatem intellegunt molestiae ancillae phaedrum inflammat factorum scribere ars exaudita huic bonas familiarem faciant pede molita nominis faciendum dum uterque affecti teneam",
                            ImgUri = "/pictures/46.jpg",
                            Name = "fortunam egregios",
                            Price = 1172.46m
                        },
                        new
                        {
                            Id = 47,
                            Description = "investigandi suppetet quamque a blanditiis cognitione consentientis quoquo involuta paria tribus percipit praeclara aliam videro morte",
                            ImgUri = "/pictures/47.jpg",
                            Name = "eloquentiam tamquam iucundum pars",
                            Price = 345.2m
                        },
                        new
                        {
                            Id = 48,
                            Description = "nullas iste propriae utamur inveneris corpus recta feci polyaeno epularum consiliisque deserunt quietus accuratius formidinum cursus maledici huc abest detractio cupiditatum suscepi causam utrum honeste multi dicturam vocet",
                            ImgUri = "/pictures/48.jpg",
                            Name = "everti pleniorem",
                            Price = 3292.18m
                        },
                        new
                        {
                            Id = 49,
                            Description = "poetae viverra conferebamus sane ludicra tractatas facillimis reprehensiones assentior cupiditate legatis praeceptrice tantopere postulet peccant referta amentur nulli euripidis iudicari praeteritas primus futuros referuntur manilium",
                            ImgUri = "/pictures/49.jpg",
                            Name = "copiosae doleamus mucius quocirca",
                            Price = 5802.43m
                        },
                        new
                        {
                            Id = 50,
                            Description = "metuamus improborum afficitur errore fugiendus amicitiae praeclare statua assiduitas successionem",
                            ImgUri = "/pictures/50.jpg",
                            Name = "urbes reiciendis illo magnus",
                            Price = 2204.53m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
